### ISSUE TITLE
Indexing on remote db server?

### ISSUE THREAD

**Issue by ggrillone** [karmi/retire#681]
I was wondering if it was possible to setup auto-indexing with tire for a database that is located on a remote server? 

I have tested this out on my local machine where my rails app was connected to my localhost db, and the auto-indexing worked perfectly when adding/deleting/updating records. However when I connected to a remote database, I had to run the 'tire:import' command manually everytime a record was added/deleted/updated. This is not ideal because I am expecting the database to reach in the millions for record count (which would take a long time to index all the data) and also data is updating very quickly so I could not simply write a background job to reindex every 5 seconds or so, I don't think that would be efficient.

**Comment by weblee** [comment]
Did you set the host up in Tire config ?

``` ruby
Tire.configure do
  url "http://hostname.com"
end
```

**Comment by ggrillone** [comment]
No, I did not. Thanks! I'll try that out and update you on if it worked or not.

**Comment by karmi** [comment]
@ggrillone Do you mean your Elasticsearch server is remote? Then setup the URL as @weblee advices. (If your _database_ is remote, then you need to configure ActiveRecord properly.)

**Comment by ggrillone** [comment]
Yes, elasticsearch would be installed on my app server, but communicating with a remote database.

**Comment by karmi** [comment]
@ggrillone How is your app connected to the database then? Could you provide more info on your setup?

**Comment by ggrillone** [comment]
Yep. It is connected to the database using the host and credentials that are setup in the database.yml file

```
development:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 5
  timeout: 5000
  port: 5432
  username: db_username
  password: db_password
  host: ip_to_remote_server
```
