### ISSUE TITLE
Could not connect to any secondary or primary nodes for replica set <Moped::Cluster nodes=[<Moped::Node resolved_address="127.0.0.1:27017">]> (1)

### ISSUE THREAD

**Issue by hyperrjas** [karmi/retire#694]
I have 3 vps servers:

**Server1** rails app with nginx,unicorn...etc. 

```
Ip Address: 111.111.111.111
```

**Server2** Mongodb database.

```
Ip Address: 222.222.222.222
```

**Server3** Elasticsearch.

```
Ip Address: 333.333.333.333
```

This is my `mongoid.yml` file:

```
development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: myappdatabase
      # Provides the hosts the default session can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: mydatabase
      username: user
      password: password
      hosts: 
        - 222.222.222.222:27017
      options:
        safe: true
  options:
    identity_map_enabled: true
```

When I try on my remote **Server1** run this code:

```
bundle exec rake environment tire:import CLASS=Object FORCE=true
```

I get the next error:

```
[IMPORT] Starting import for the 'Object' class
--------------------------------------------------------------------------------
rake aborted!
Could not connect to any secondary or primary nodes for replica set <Moped::Cluster nodes=[<Moped::Node resolved_address="127.0.0.1:27017">]>
```

**How can I fix this error and connect mongodb server with `tire/elasticsearch` server?**

Thank you!
