### ISSUE TITLE
Worth mentioning `encoding: utf8` in database.yml?

### ISSUE THREAD

**Issue by ramontayag** [karmi/retire#86]
I was trying to index a bunch of text that had accents in them, and I was getting errors from ElasticSearch.

```
ree-1.8.7-2011.03 :018 > Artist.elasticsearch_index.import [Artist.find(24871)]
 => "{\"took\":1,\"items\":[{\"index\":{\"_index\":\"artists\",\"_type\":\"artist\",\"_id\":\"24871\",\"error\":\"MapperParsingException[Failed to parse [name]]; nested: JsonParseException[Invalid UTF-8 middle byte 0x20\\n at [Source: [B@44e31cad; line: 1, column: 16]]; \"}}]}" 
```

My colleague @corroded did some research and entered `encoding: utf8` in the database.yml. And now it works!

It might be worth mentioning this somewhere, even if it's not directly related to tire. It will probably save others some time.

Sample:

```
development:
  adapter: mysql
  username: asdasd
  password:
  socket: /var/mysql/mysql.sock
  encoding: utf8
```
